[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "libGL"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:${PORT:-8080}"
